# Generated by Django 4.1.3 on 2023-09-30 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Başlık',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('başlık', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Birim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birim', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diğerbaşlık',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('başlık', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Düzensizkategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faturabaşlık',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('başlık', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gelir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaynak', models.CharField(max_length=255)),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('birim', models.CharField(choices=[('TL', 'Türk Lirası'), ('RUB', 'Rus Rublesi'), ('ALTIN', 'Altın'), ('USD', 'Dolar'), ('EUR', 'Euro')], max_length=50)),
                ('tarih', models.DateField(verbose_name='Tarih')),
            ],
        ),
        migrations.CreateModel(
            name='Gıdakategorisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('başlık', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Harcayan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('başlık', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kategorisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('başlık', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Renk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renkadı', models.CharField(max_length=100)),
                ('renkcode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sahibi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('başlık', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ödemedetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=100)),
                ('taksitsayısı', models.CharField(blank=True, max_length=100)),
                ('tutar', models.CharField(blank=True, max_length=100)),
                ('ödemeilk', models.DateField(blank=True, verbose_name='Ödeme Tarihi')),
                ('ödemeson', models.DateField(blank=True, verbose_name='Son Ödeme Tarihi')),
                ('ödendimi', models.BooleanField(blank=True)),
                ('notekle', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('başlık', models.CharField(max_length=100)),
                ('notekle', models.TextField(blank=True)),
                ('yapıldımı', models.BooleanField(blank=True)),
                ('detay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wejegeh.renk')),
            ],
        ),
        migrations.CreateModel(
            name='Kartlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sahibi', models.CharField(max_length=10)),
                ('toplam_borç', models.DecimalField(decimal_places=2, max_digits=10)),
                ('güncelleme_tarihi', models.DateField(blank=True, verbose_name='Güncelleme Tarihi')),
                ('notekle', models.TextField(blank=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wejegeh.düzensizkategori')),
            ],
        ),
        migrations.CreateModel(
            name='Gıda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('başlık', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wejegeh.başlık')),
                ('birim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wejegeh.birim')),
                ('harcayan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wejegeh.harcayan')),
                ('kategorisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wejegeh.gıdakategorisi')),
            ],
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('harcayan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wejegeh.harcayan')),
                ('kategorisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wejegeh.faturabaşlık')),
            ],
        ),
        migrations.CreateModel(
            name='Düzensizm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ödemeson', models.DateField(blank=True, verbose_name='Son Ödeme Tarihi')),
                ('ödendimi', models.BooleanField(blank=True)),
                ('notekle', models.TextField(blank=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wejegeh.düzensizkategori')),
                ('sahibi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wejegeh.sahibi')),
            ],
        ),
        migrations.CreateModel(
            name='Düzensize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ödemeson', models.DateField(blank=True, verbose_name='Son Ödeme Tarihi')),
                ('ödendimi', models.BooleanField(blank=True)),
                ('notekle', models.TextField(blank=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wejegeh.düzensizkategori')),
                ('sahibi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wejegeh.sahibi')),
            ],
        ),
        migrations.CreateModel(
            name='Düzensiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ödemeson', models.DateField(blank=True, verbose_name='Son Ödeme Tarihi')),
                ('ödendimi', models.BooleanField(blank=True)),
                ('notekle', models.TextField(blank=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wejegeh.düzensizkategori')),
                ('sahibi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wejegeh.sahibi')),
            ],
        ),
        migrations.CreateModel(
            name='DüzenliÖdeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=100)),
                ('toplamtaksit', models.CharField(blank=True, max_length=100)),
                ('notekle', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('detay', models.ManyToManyField(blank=True, to='wejegeh.ödemedetay')),
            ],
        ),
        migrations.CreateModel(
            name='Diğer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('başlık', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wejegeh.diğerbaşlık')),
                ('birim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wejegeh.birim')),
                ('harcayan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wejegeh.harcayan')),
                ('kategorisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wejegeh.kategorisi')),
            ],
        ),
    ]
